### ISSUE TITLE
Error: call of overloaded ‘abs(unsigned int)’ is ambiguous

### ISSUE THREAD

**Issue by wclee47** [broadinstitute/CODECsuite#1]
Hi, thanks a lot for making this program available.
I tried to install it and ran into the following error message.
Can you please take a look? I'm using GCC 11.2.0.

In file included from CODECsuite/trimadapter.cpp:11: CODECsuite/include/Adapter.h:495:12: error: call of overloaded ‘abs(unsigned int)’ is ambiguous
495 |         abs(rc_cds_mb.start_j - rc_cds_mb.start_i) <= junction_adapter_min_len_ * 0.1) // matched in similar distance to beginning

**Comment by ruolin** [comment]
Hi @wclee47, thank you for reporting the bug. I can reproduce this error under GCC7.3. It seems to be related to a modern GCC complier issues. BTW, I had been using GCC5.2. I had fix it now. Can you try this branch https://github.com/broadinstitute/CODECsuite/tree/hotfix

**Comment by wclee47** [comment]
Thank you for the quick update! I managed to finish the compilation with the updated version.
However, there were several additional issues which I addressed by the solutions I found online.

For example, 

CODECsuite/bbcpputil/include/BamRecordExt.h:50:50: error: 'numeric_limits' is not a member of 'std'
=> I added "#include <limits>"

It will be appreciated if you can test the whole pipeline with the up-to-date compilers that most people are likely to use.

Anyway I successfully compiled the program!

Thanks,

Won-Chul

**Comment by wclee47** [comment]
Thank you for the quick update! I managed to finish the compilation with the updated version.
However, there were several additional issues which I addressed by the solutions I found online.

For example,

CODECsuite/bbcpputil/include/BamRecordExt.h:50:50: error: 'numeric_limits' is not a member of 'std'
=> I added "#include <limits>"

It will be appreciated if you can test the whole pipeline with the up-to-date compilers that most people are likely to use.

Anyway I successfully compiled the program!

Thanks,

Won-Chul
