### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by waalkes** [broadinstitute/CODECsuite#15]
Thanks for making this available.  I follow the installation instructions but get the following error message:

ar: `u' modifier ignored since `D' is the default (see `U')
/usr/bin/ld: ./libfml.a(rope.o):/mnt/programs/CODECsuite/bbcpputil/third_party/SeqLib/fermi-lite/rle.h:33: multiple definition of `rle_auxtab'; ./libfml.a(misc.o):/mnt/programs/CODECsuite/bbcpputil/third_party/SeqLib/fermi-lite/rle.h:33: first defined here
/usr/bin/ld: ./libfml.a(rle.o):/mnt/programs/CODECsuite/bbcpputil/third_party/SeqLib/fermi-lite/rle.h:33: multiple definition of `rle_auxtab'; ./libfml.a(misc.o):/mnt/programs/CODECsuite/bbcpputil/third_party/SeqLib/fermi-lite/rle.h:33: first defined here
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:20: fml-asm] Error 1
make[4]: *** [Makefile:358: all-recursive] Error 1
make[3]: *** [Makefile:299: all] Error 2
make[2]: *** [CMakeFiles/SeqLib.dir/build.make:86: SeqLib-prefix/src/SeqLib-stamp/SeqLib-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/SeqLib.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

Any ideas?
Thanks.

**Comment by ruolin** [comment]
which version of g++ was used?

**Comment by waalkes** [comment]
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by ruolin** [comment]
some third party tools are not compatible with modern compilers. I plan to fix that but haven't able to. If you can, please tried 7.3 in the meanwhile.

**Comment by waalkes** [comment]
Do you have binaries available somewhere?  Thanks for the help on this.

**Comment by ruolin** [comment]
here is one https://github.com/broadinstitute/CODECsuite/releases/tag/v1.0.2

**Comment by waalkes** [comment]
I found a machine running 18.04 and built it there and it compiled correctly and appears to run fine on 22.04
