### ISSUE TITLE
SampleSheet issue

### ISSUE THREAD

**Issue by waalkes** [broadinstitute/CODECsuite#16]
I am trying to demux as directed.   The documentation tells me the sample sheet should be a csv(comma separated values) file:

"The first step is demultiplexing and it requires a sample sheet in csv format for each lane which looks the following."

I tried that and it didn't work and the error says the sample sheet should be tab delimited so I tried that and it didn't work either.

Can you specify what the format of the sample sheet should be?

tron:/mnt//BaseCalls $ cat /mnt/BaseCalls/SampleSheet.csv
SampleName,IndexBarcode1,IndexBarcode2
lambda_1,CTTGAACGGACTGTCCAC,CACCGAGCGTTAGACTAC
lambda_2,GAGCCTACTCAGTCAACG,GTGTCGAACACTTGACGG
lambda_3,GCTTGTAAGGCAGGTTAG,CTGATCTTCAGCTGACTG
lambda_4,CAAGCGTCTTACATGGTC,GAATCTGAGGCACTGTAC
tron:/mnt/BaseCalls $ /mnt/programs/CODECsuite/build/codec demux -1 CODEC-4samples_S1_L001_R1_001.fastq.gz -2 CODEC-4samples_S1_L001_R2_001.fastq.gz -p SampleSheet.csv -o demux_out
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid index file
 Format required as three tab-delimited columns with header SampleName  IndexBarcode1   IndexBarcode2
Aborted (core dumped)
tron:/mnt/BaseCalls $ cat SampleSheet_tab.csv
SampleName      IndexBarcode1   IndexBarcode2
lambda_1        CTTGAACGGACTGTCCAC      CACCGAGCGTTAGACTAC
lambda_2        GAGCCTACTCAGTCAACG      GTGTCGAACACTTGACGG
lambda_3        GCTTGTAAGGCAGGTTAG      CTGATCTTCAGCTGACTG
lambda_4        CAAGCGTCTTACATGGTC      GAATCTGAGGCACTGTAC
tron:/mnt/BaseCalls $ /mnt/programs/CODECsuite/build/codec demux -1 CODEC-4samples_S1_L001_R1_001.fastq.gz -2 CODEC-4samples_S1_L001_R2_001.fastq.gz -p SampleSheet_tab.csv -o demux_out
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid index file
 Format required as three tab-delimited columns with header SampleName  IndexBarcode1   IndexBarcode2
Aborted (core dumped)

Thanks

**Comment by ruolin** [comment]
Hi @waalkes sorry about the confusion caused by the error message. The website is correct. It requires a csv file not tsv file. I will change the error msg. And meanwhile, you first file pasted in the chat look okay to me. Does it contain any hidden characters? Can you pass me the file so I can check for you.

**Comment by waalkes** [comment]
Thanks.  I did look at it for hidden characters in vi but I didn't see any.  Here it is.  Note we used 4 of the barcodes from your paper which the 3rd and 4th I believe were different than the barcodes you list on the website.  samplesheet is attached.
[SampleSheet.csv](https://github.com/broadinstitute/CODECsuite/files/13866383/SampleSheet.csv)

**Comment by ruolin** [comment]
I tested your SampleSheet.csv and it did run through. You mentioned in your other thread that you built a version in 18.04 and ran it on 22.04. It shouldn't give this problem but could you test your binary back on 18.04?

**Comment by ruolin** [comment]
On the other note, The barcodes (3rd and 4th) on the websites shifted 1 base to the right compared to the one in the paper. This is to ensure the universal trimming options for all barcodes with option  `codec trim -u 3 -f 2`. This means the first three bps are UMI and then next two bps are discarded.

**Comment by waalkes** [comment]
That worked.  Thanks.

**Comment by waalkes** [comment]
closed

**Comment by waalkes** [comment]
closed

**Comment by jmd5596** [comment]
Hello, I am having a similar issue when trying to demultiplex. This is the error message: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid index file
/var/spool/slurmd/job1371685/slurm_script: line 37:  7752 Aborted                 /storage/goodell/home/u244950/CODECsuite/build/codec demux --q1 "${JDIRECTORY_PATH}/fastq/Undetermined_S0_L001_R1_001.fastq.gz" --q2 "${JDIRECTORY_PATH}/fastq/Undetermined_S0_L001_R2_001.fastq.gz" --library_param "${JDIRECTORY_PATH}/clonewars2.csv" --outprefix demux_outprefix

I've included all the modules I used to compile the CODEC suite in the bash script but keep getting the same error. Any advice?
