### ISSUE TITLE
demultiplexing_issue

### ISSUE THREAD

**Issue by jmd5596** [broadinstitute/CODECsuite#18]
Hello, first thank you for creating this tool!

I am having some trouble trying to demultiplex. This is my code:
/storage/goodell/home/u244950/CODECsuite/build/codec demux --q1 ./fastq/Undetermined_S0_L001_R1_001.fastq.gz --q2 ./fastq/Undetermined_S0_L001_R2_001.fastq.gz --library_param clonewars2.csv --outprefix demux_outprefix

Here is the error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid index file
 Format required as three comma-delimited columns with header SampleName,IndexBarcode1,IndexBarcode2
Aborted (core dumped)

I've checked the format of the sample sheet and there are no hidden characters in the file. I do only have two samples that we were testing, here is the sample sheet
SampleName,IndexBarcode1,IndexBarcode2
sample01,GAGCCTACTCAGTCAACG,GTGTCGAACACTTGACGG
sample02,CTTGAACGGACTGTCCAC,CACCGAGCGTTAGACTAC

**Comment by ruolin** [comment]
What is your GCC version?

**Comment by jmd5596** [comment]
I'm using 7.3.0.

**Comment by jmd5596** [comment]
When building the package this is the process I went through before cloning the package:
module load gnu/binutils/2.41
module load cmake/3.29.2
module load gnu/make/4.4
module load gnu/gcc/7.3.0
export LD_LIBRARY_PATH=/share/apps/dwarf/0.9.2/lib:/share/apps/elfutils/0.191/lib/:$LD_LIBRARY_PATH
export LD_RUN_PATH=/share/apps/dwarf/0.9.2/lib:/share/apps/elfutils/0.191/lib/:$LD_RUN_PATH
export C_INCLUDE_PATH=/share/apps/dwarf/0.9.2/include:/share/apps/elfutils/0.191/include:$C_INCLUDE_PATH

**Comment by ruolin** [comment]
Thanks for confirming your system setup. I have some rough idea of what is happening. Can you try this quick fix to see if this work? https://github.com/broadinstitute/CODECsuite/tree/hot_fix.  If this isn't working, I have to mirror your environment to be able to reproduce the error.

**Comment by jmd5596** [comment]
It did not work for me, I am still getting the same error. I implemented the changes to the index.h and snakefile, then created a separate build directory and tried this executable.

**Comment by ruolin** [comment]
I suspect there is some issues with the build. In that case, I build a binary for you using GNU7.3. https://github.com/broadinstitute/CODECsuite/releases/tag/v1.1.1 
Could you try if this work for you or not?

**Comment by jmd5596** [comment]
The compilation runs into an error: 
SeqLib not found
CMake Error at /share/apps/cmake/3.29.2/share/cmake-3.29/Modules/ExternalProject.cmake:3270 (message):
  No download info given for 'SeqLib' and its source directory:

   /storage/goodell/home/u244950/CODECsuite-1.1.1/bbcpputil/third_party/SeqLib

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * DOWNLOAD_COMMAND
   * URL
   * GIT_REPOSITORY
   * SVN_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
Call Stack (most recent call first):
  /share/apps/cmake/3.29.2/share/cmake-3.29/Modules/ExternalProject.cmake:4456 (_ep_add_download_command)
  CMakeLists.txt:38 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!

**Comment by ruolin** [comment]
Hi you can try the binary file instead of compiling and building from scratch. You can download it with `wget https://github.com/broadinstitute/CODECsuite/releases/download/v1.1.1/codec`

**Comment by jmd5596** [comment]
I am still getting the same error. I created a new conda environment for the binary, loaded gcc 7.3, and made the file executable.

**Comment by jmd5596** [comment]
So I checked the c++ version which is also 7.3, could that be the issue?

**Comment by ruolin** [comment]
Hi @jmd5596 , I cannot really reproduce your error. Could you try writing some print functions at the code here https://github.com/broadinstitute/CODECsuite/blob/master/include/Index.h#L95 and see what is going on?

**Comment by ruolin** [comment]
@jmd5596 Have you found a solution yet? We have made a CODEC docker for you to try: http://us.gcr.io/tag-public/codec:v1.1.1. Once you pull the docker you can use `/CODECsuite/build/codec demux -1 ${paired_fastqs.left} -2 ${paired_fastqs.right} -p ${sample_sheet} -o ${batch_id}_split.${split} > ${batch_id}_split.${split}.log`

**Comment by jmd5596** [comment]
The docker pull helped!
