### ISSUE TITLE
when trying to clone CODECsuite , its giving error. 

### ISSUE THREAD

**Issue by AKSHARA-8** [broadinstitute/CODECsuite#8]
git clone --recursive git@github.com:broadinstitute/CODECsuite.git
Cloning into 'CODECsuite'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(base) nikhil@jarvis:~/codec_duplex/codeccheck$ git clone --recursive https://github.com/broadinstitute/CODECsuite.git
Cloning into 'CODECsuite'...
remote: Enumerating objects: 960, done.
remote: Counting objects: 100% (439/439), done.
remote: Compressing objects: 100% (248/248), done.
remote: Total 960 (delta 201), reused 410 (delta 185), pack-reused 521
Receiving objects: 100% (960/960), 97.22 MiB | 14.62 MiB/s, done.
Resolving deltas: 100% (500/500), done.
Submodule 'bbcpputil/third_party/SeqLib' (git@github.com:ruolin/SeqLib.git) registered for path 'bbcpputil/third_party/SeqLib'
Submodule 'bbcpputil/third_party/backward-cpp' (https://github.com/bombela/backward-cpp) registered for path 'bbcpputil/third_party/backward-cpp'
Submodule 'bbcpputil/third_party/seqan' (git@github.com:ruolin/seqan.git) registered for path 'bbcpputil/third_party/seqan'
Submodule 'bbcpputil/third_party/spoa' (git@github.com:rvaser/spoa.git) registered for path 'bbcpputil/third_party/spoa'
Cloning into '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/SeqLib'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ruolin/SeqLib.git' into submodule path '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/SeqLib' failed
Failed to clone 'bbcpputil/third_party/SeqLib'. Retry scheduled
Cloning into '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/backward-cpp'...
remote: Enumerating objects: 1075, done.
remote: Counting objects: 100% (203/203), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 1075 (delta 141), reused 144 (delta 120), pack-reused 872
Receiving objects: 100% (1075/1075), 777.11 KiB | 14.66 MiB/s, done.
Resolving deltas: 100% (650/650), done.
Cloning into '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/seqan'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ruolin/seqan.git' into submodule path '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/seqan' failed
Failed to clone 'bbcpputil/third_party/seqan'. Retry scheduled
Cloning into '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/spoa'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:rvaser/spoa.git' into submodule path '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/spoa' failed
Failed to clone 'bbcpputil/third_party/spoa'. Retry scheduled
Cloning into '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/SeqLib'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ruolin/SeqLib.git' into submodule path '/home/nikhil/codec_duplex/codeccheck/CODECsuite/bbcpputil/third_party/SeqLib' failed
Failed to clone 'bbcpputil/third_party/SeqLib' a second time, aborting

**Comment by ruolin** [comment]
Hi @AKSHARA-8. It does not seem like you setup your ssh-key pair correctly on your github. Can you follow this article?https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
